###
POST http://localhost:3020/users/
Content-Type: application/json

{
 "user_name":"chandhana",
  "password":"chandhana@2003",
  "phone_number":"1564587809",
  "email_id":"chandhana@gmail.com",
  "organization_id":"1",
  "default_bus_id":"4",
  "my_stop":"21"
}

###
post http://localhost:3020/driver/
Content-Type: application/json

{
    "driver_name": "driver_16",
    "phone_number": "1111111111",
    "location": "p",
    "bus_id": 18,
    "username": "user16",
    "password": "password16"
  }

###
post http://localhost:3020/driver/login
Content-Type: application/json

{
  "username": "user16",
  "password":"password16"
}

###
post http://localhost:3020/login
Content-Type: application/json

{
  "user_name": "laasya",
  "password":"laasya@2003"
}

###
post http://localhost:3020/driver/login/
Content-Type: application/json

{
  "user_name": "user1",
  "password":"password1"
}

###
get http://localhost:3020/drivers/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJjaGFuZGhhbmEiLCJpYXQiOjE2OTk3MDY0MDl9.JnbPlsCWJsFKLqONpQrrPcgweA4opUGOWmSKKvwOQVM
###
get http://localhost:3020/users/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJjaGFuZGhhbmEiLCJpYXQiOjE2OTk3MDY0MDl9.JnbPlsCWJsFKLqONpQrrPcgweA4opUGOWmSKKvwOQVM
###
put   http://localhost:3020/users/1/phone_number
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJMYWFzeWEiLCJpYXQiOjE2OTUzMTc3NDd9.8uHH9hpexns1wnYOorTmyKegfDn7TpNHMLnoka1mDwg
Content-Type: application/json

{
 "phone_number":"9876543210"
}

###
get  http://localhost:3020/busStops/18
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJMYWFzeWEiLCJpYXQiOjE2OTcxNzA0MjN9.q0F7XN8V9k4pkuQD764MW7Pmp3HumkqBwQc99JX38wA

###
post http://localhost:3020/driver/1/location
Content-Type: application/json

{
  "user_name": "Laasya",
  "password":"lassya@2002"
}

###
GET http://localhost:3020/driver/busID/6
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJMYWFzeWEiLCJpYXQiOjE2OTg2NjU5OTN9.xd_T4ukFsS-2arTV9sRjvpB9JD_NzNa4R6dd9PkQaL0

###
get http://localhost:3020/buses
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJMYWFzeWEiLCJpYXQiOjE2OTg2NjU5OTN9.xd_T4ukFsS-2arTV9sRjvpB9JD_NzNa4R6dd9PkQaL0

###
post http://localhost:3020/msg
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjQyMjI0MTk2Mzg1MDk5NDAsInVzZXJfbmFtZSI6ImxhYXN5YSIsIlBBU1NXT1JEIjoiJDJiJDEwJDIuc2p0cll5WXdhbVpPaTF2NmxSM2VPdWJuLjVaN1hOaU9KeVc3ajRpbDkxaHVvbzBGS015IiwicGhvbmVfbnVtYmVyIjoiOTcwMzYyMzIzMiIsImVtYWlsX2lkIjoibGFhc3lhQGdtYWlsLmNvbSIsIm9yZ2FuaXphdGlvbl9pZCI6MSwiZGVmYXVsdF9idXNfaWQiOjEsIm15X3N0b3AiOiJHdW50dXIgQnVzIFN0YW5kIiwiaWF0IjoxNjk5ODYwNzMxfQ.Aq6PDftMCDpyRA-kQ-4kCWPZ0DsVqlc2m-i1WE4YtIA

###
put http://localhost:3020/driver/1/location
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjQyMjI0MTk2Mzg1MDk5NDAsInVzZXJfbmFtZSI6ImxhYXN5YSIsIlBBU1NXT1JEIjoiJDJiJDEwJDIuc2p0cll5WXdhbVpPaTF2NmxSM2VPdWJuLjVaN1hOaU9KeVc3ajRpbDkxaHVvbzBGS015IiwicGhvbmVfbnVtYmVyIjoiOTcwMzYyMzIzMiIsImVtYWlsX2lkIjoibGFhc3lhQGdtYWlsLmNvbSIsIm9yZ2FuaXphdGlvbl9pZCI6MSwiZGVmYXVsdF9idXNfaWQiOjEsIm15X3N0b3AiOiJHdW50dXIgQnVzIFN0YW5kIiwiaWF0IjoxNjk5ODYwNzMxfQ.Aq6PDftMCDpyRA-kQ-4kCWPZ0DsVqlc2m-i1WE4YtIA
Content-Type: application/json

{
  "longitude": "0",
  "latitude":"0"
}